version: "3.8"

services:
  towelgpt_api:
    image: towelgpt_api
    container_name: towelgpt_api
    restart: always #restart on error (usually code compilation from save during bad state)
    ports:
      - "4891:4891"
    environment:
      - APP_ENVIRONMENT=dev
      - WEB_CONCURRENCY=2
      - LOGLEVEL=debug
      - PORT=4891
      - model=ggml-mpt-7b-chat.bin
      - inference_mode=cpu
    volumes:
      - './towelgpt_api/app:/app'
    command: ["/start-reload.sh"]